### ISSUE TITLE
Feature Request: Capture replies

### ISSUE THREAD

**Issue by bexelbie** [Xacnio/tweetcapture#14]
This is a great tool.  Thank you!

Have you considered an option to captures replies to tweets along with the original tweet?

**Comment by Xacnio** [comment]
Replies added as two different parts:
1- Show parent tweets
2- Show mentions

On second one, only the first replies are visible on mention count property because mention count might be too much, and "show more" function not supported on tweets for now.

Check the examples: https://github.com/Xacnio/tweetcapture#show-mentions-example

Version: 0.1.0 #15
Version: 0.1.1 #16
